/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import gestion_biblio.Gestion_biblio;
import gestion_biblio.Parametre;
import gestion_biblio.db_connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ~chaimae~
 */
public class etudiant extends javax.swing.JFrame {
 ResultSet rs;
    db_connection db;
    /**
     * Creates new form etudient
     */
    public etudiant() {
        db = new db_connection(new Parametre().HOST_DB, new Parametre().USERNAME_DB, new Parametre().PASSWORD_DB, new Parametre().IPHOST, new Parametre().PORT);
        initComponents();
        tableetudiant(); 
        //actualiseretudiant();
   
    }
    
      public void tableetudiant() {
        String a[] = {"identifiant", "nom", "prenom", "email"};
        rs = db.querySelect(a, "etudiant");
        table_etudiant.setModel(new Gestion_biblio(rs));}
      
      
        public void actualiseretudiant() {
        txt_nome.setText("");
        txt_prenome.setText("");
        txt_emaile.setText("");
        txt_rech.setText("");
        pp4.setText("");
       
        
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_etudiant = new javax.swing.JTable();
        txt_nome = new javax.swing.JTextField();
        txt_prenome = new javax.swing.JTextField();
        txt_emaile = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        com_re = new javax.swing.JComboBox<>();
        txt_rech = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel161 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel162 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jButton31 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pp4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_etudiant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "identifiant", "nom", "prenom", "email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_etudiant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_etudiantMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_etudiant);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 660, 110));

        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 180, 30));

        txt_prenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_prenomeActionPerformed(evt);
            }
        });
        getContentPane().add(txt_prenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 180, 30));

        txt_emaile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emaileActionPerformed(evt);
            }
        });
        getContentPane().add(txt_emaile, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 180, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nom :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 100, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Prénom :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, 20));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, 20));

        com_re.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "identifiant", "nom", "prenom", "email", " " }));
        getContentPane().add(com_re, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 190, 30));

        txt_rech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rechActionPerformed(evt);
            }
        });
        getContentPane().add(txt_rech, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 190, 30));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("recherche par catégorie :");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, 30));

        jLabel34.setFont(new java.awt.Font("Webdings", 0, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 30, 40));

        jLabel33.setFont(new java.awt.Font("Wingdings 2", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 20, 40));

        jLabel35.setFont(new java.awt.Font("Webdings", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, 30, 40));

        jLabel161.setFont(new java.awt.Font("Webdings", 0, 24)); // NOI18N
        jLabel161.setForeground(new java.awt.Color(255, 255, 255));
        jLabel161.setText("");
        getContentPane().add(jLabel161, new org.netbeans.lib.awtextra.AbsoluteConstraints(1204, 0, 30, 40));

        jLabel36.setFont(new java.awt.Font("Wingdings 2", 0, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, -1, 40));

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Rechercher");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 130, 40));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Ajouter");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 130, 40));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Modifier");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 130, 40));

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Supprimer");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 130, 40));

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("  Actualiser");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 120, 40));

        jLabel6.setBackground(new java.awt.Color(204, 204, 255));
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel6.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel6AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 410, 200));

        jLabel162.setFont(new java.awt.Font("Webdings", 0, 24)); // NOI18N
        jLabel162.setForeground(new java.awt.Color(255, 255, 255));
        jLabel162.setText("");
        getContentPane().add(jLabel162, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 30, 40));

        jLabel63.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("");
        jLabel63.setToolTipText("");
        getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, 20, 40));

        jButton31.setBackground(new java.awt.Color(0, 0, 0));
        jButton31.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton31.setForeground(new java.awt.Color(255, 255, 255));
        jButton31.setText("Retour");
        jButton31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton31.setOpaque(false);
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 120, 40));

        jPanel1.setBackground(new java.awt.Color(56, 68, 84));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pp4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pp4.setForeground(new java.awt.Color(0, 204, 51));
        jPanel1.add(pp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 250, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_etudiantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_etudiantMouseClicked
        txt_nome.setText(String.valueOf(table_etudiant.getValueAt(table_etudiant.getSelectedRow(), 1)));
        txt_prenome.setText(String.valueOf(table_etudiant.getValueAt(table_etudiant.getSelectedRow(), 2)));
        txt_emaile.setText(String.valueOf(table_etudiant.getValueAt(table_etudiant.getSelectedRow(), 3)));
        //comty.setSelectedItem(String.valueOf(tbl_user.getValueAt(tbl_user.getSelectedRow(), 4)));
    }//GEN-LAST:event_table_etudiantMouseClicked

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeActionPerformed

    private void txt_prenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_prenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prenomeActionPerformed

    private void txt_emaileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emaileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emaileActionPerformed

    private void jLabel6AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel6AncestorAdded

    }//GEN-LAST:event_jLabel6AncestorAdded

    private void txt_rechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rechActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (txt_rech.getText().equals("")  ) {
            JOptionPane.showMessageDialog(this, "SVP entrer vos donneés");
        } else {
            if (com_re.getSelectedItem().equals("identifiant")) {
                rs = db.querySelectAll("etudiant", "identifiant LIKE '%" + txt_rech.getText() + "%' ");
                table_etudiant.setModel(new Gestion_biblio(rs));
            } else if (com_re.getSelectedItem().equals("nom")) {
                rs = db.querySelectAll("etudiant", "nom LIKE '%" + txt_rech.getText() + "%' ");
                table_etudiant.setModel(new Gestion_biblio(rs));
            } else if (com_re.getSelectedItem().equals("prenom")) {
                rs = db.querySelectAll("etudiant", "prenom LIKE '%" + txt_rech.getText() + "%' ");
                table_etudiant.setModel(new Gestion_biblio(rs));
            } else if (com_re.getSelectedItem().equals("email")) {
                rs = db.querySelectAll("etudiant", "email LIKE '%" + txt_rech.getText() + "%' ");
                table_etudiant.setModel(new Gestion_biblio(rs));

            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (txt_nome.getText().equals("") || txt_prenome.getText().equals("") || txt_emaile.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "SVP entrer les informations complètes");
        } else {
            String[] colon = { "nom", "prenom", "email"};
            String[] inf = {txt_nome.getText(), txt_prenome.getText(), txt_emaile.getText()};
            System.out.println(db.queryInsert("etudiant", colon, inf));
            tableetudiant();
            actualiseretudiant();
            pp4.setText("ajouter avec succès");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (txt_nome.getText().equals("") || txt_prenome.getText().equals("") || txt_emaile.getText().equals("")
        ) {
            JOptionPane.showMessageDialog(this, "SVP entrer les informations complètes");
        } else {
            String[] colon = {"nom", "prenom", "email"};
            String[] inf = {txt_nome.getText(), txt_prenome.getText(), txt_emaile.getText()};
            String id = String.valueOf(table_etudiant.getValueAt(table_etudiant.getSelectedRow(), 0));
            System.out.println(db.queryUpdate("etudiant", colon, inf, "identifiant='" + id + "'"));
            tableetudiant();
            actualiseretudiant();  
            pp4.setText("Modifié avec succès");}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (txt_nome.getText().equals("") || txt_prenome.getText().equals("") || txt_emaile.getText().equals("")
        ) {
            JOptionPane.showMessageDialog(this, "SVP entrer les informations complètes");
        }else{
            String id = String.valueOf(table_etudiant.getValueAt(table_etudiant.getSelectedRow(), 0));
            if (JOptionPane.showConfirmDialog(this, "Etes-vous sûr que vous voulez supprimer ?", "attention!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                db.queryDelete("etudiant", "identifiant=" + id);
            } else {
                return;
            }
            tableetudiant();
        pp4.setText("Supprimer avec succès");}
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        actualiseretudiant();
        tableetudiant();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        Principal_A l = null;
     try {
         l = new  Principal_A();
     } catch (SQLException ex) {
         Logger.getLogger(etudiant.class.getName()).log(Level.SEVERE, null, ex);
     }
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton31ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new etudiant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> com_re;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pp4;
    private javax.swing.JTable table_etudiant;
    private javax.swing.JTextField txt_emaile;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_prenome;
    private javax.swing.JTextField txt_rech;
    // End of variables declaration//GEN-END:variables
}
