/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import gestion_biblio.Gestion_biblio;
import gestion_biblio.db_connection;
import gestion_biblio.Parametre;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ~chaimae~
 */
public class Principal extends javax.swing.JFrame {
   ResultSet rs;
    db_connection db;
    /**
     * Creates new form Principale
     */
    public Principal() {   
       db = new db_connection(new Parametre().HOST_DB, new Parametre().USERNAME_DB, new Parametre().PASSWORD_DB, new Parametre().IPHOST, new Parametre().PORT);
        initComponents();
        table1(); 
        jam();
    }
       public void table1() {
        String a[] = {"idAdministrateur","Nom","Prénom","Email","Mot_passe","type"};
        rs = db.querySelect(a, "administrateur");
        table_admin.setModel(new Gestion_biblio(rs));
    }
     public void jam() {
        Date s = new Date();
        SimpleDateFormat tgl = new SimpleDateFormat("EEEE-dd-MMM-yyyy");
        SimpleDateFormat jam = new SimpleDateFormat("HH:mm");
        date.setText(jam.format(s));
        heure.setText(tgl.format(s));}
         
        public void actualiser() {
        txt_nom.setText("");
        txt_prenom.setText("");
        txt_email.setText("");
        txt_mot_passe.setText("");
        compty.setSelectedItem("Typpppe");
        pp5.setText("");
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel6 = new javax.swing.JLabel();
        jButton33 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        heure = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        mvt = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_admin = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txt_mot_passe = new javax.swing.JTextField();
        txt_prenom = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txt_nom = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        txt_rech = new javax.swing.JTextField();
        com_re = new javax.swing.JComboBox<>();
        jLabel161 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        compty = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        pp5 = new javax.swing.JLabel();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Webdings", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 40, 40));
        jLabel6.getAccessibleContext().setAccessibleName("");

        jButton33.setBackground(new java.awt.Color(0, 0, 0));
        jButton33.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton33.setForeground(new java.awt.Color(255, 255, 255));
        jButton33.setText("    Déconnexion  ");
        jButton33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1205, 0, 140, 40));

        jTabbedPane1.setBackground(new java.awt.Color(255, 204, 102));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1000, 1000));

        jPanel1.setBackground(new java.awt.Color(56, 68, 84));
        jPanel1.setLayout(null);

        heure.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        heure.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.add(heure);
        heure.setBounds(10, 0, 250, 30);

        date.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        date.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.add(date);
        date.setBounds(230, 0, 140, 30);

        mvt.setBackground(new java.awt.Color(255, 204, 102));
        mvt.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        mvt.setForeground(new java.awt.Color(255, 153, 51));
        mvt.setText("Bienvenue dans votre bibliothèque");
        mvt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                mvtPropertyChange(evt);
            }
        });
        jPanel1.add(mvt);
        mvt.setBounds(180, 40, 900, 100);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/image/Library-Management-Banner.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(530, 110, 940, 580);

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/Interface/image/home.png")), jPanel1); // NOI18N

        jPanel2.setBackground(new java.awt.Color(56, 68, 84));
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nom", "Prénom", "Email", "Mot_passe", "type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_adminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                table_adminMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(table_admin);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 780, 100));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("recherche par catégorie :");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, 30));

        jLabel33.setFont(new java.awt.Font("Wingdings 2", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 20, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Type  :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 130, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nom :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 100, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Prénom :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, 20));

        jLabel34.setFont(new java.awt.Font("Webdings", 0, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 30, 40));

        txt_mot_passe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mot_passeActionPerformed(evt);
            }
        });
        jPanel2.add(txt_mot_passe, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 180, 30));

        txt_prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_prenomActionPerformed(evt);
            }
        });
        jPanel2.add(txt_prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 180, 30));

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        jPanel2.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 180, 30));

        jLabel36.setFont(new java.awt.Font("Wingdings 2", 0, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, -1, 40));

        jLabel35.setFont(new java.awt.Font("Webdings", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, 30, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ajouter");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 130, 40));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Modifier");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 130, 40));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Supprimer");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 130, 40));

        txt_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomActionPerformed(evt);
            }
        });
        jPanel2.add(txt_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 180, 30));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Rechercher");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 130, 40));
        jPanel2.add(txt_rech, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 190, 30));

        com_re.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nom", "Prénom", "Email", "Type", " " }));
        jPanel2.add(com_re, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 190, 30));

        jLabel161.setFont(new java.awt.Font("Webdings", 0, 24)); // NOI18N
        jLabel161.setForeground(new java.awt.Color(255, 255, 255));
        jLabel161.setText("");
        jPanel2.add(jLabel161, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, -1, 40));

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("  Actualiser");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, 130, 40));

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 330, 210));

        compty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        compty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Responsable", "Administrateur" }));
        jPanel2.add(compty, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 180, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mot de passe  :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 150, 20));

        pp5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pp5.setForeground(new java.awt.Color(0, 204, 51));
        jPanel2.add(pp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 250, 30));

        jTabbedPane1.addTab("Gestion des administrateurs", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 710));
        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed

        LOGIN l=new LOGIN();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        actualiser();
        table1();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (txt_rech.getText().equals("")  ) {
            JOptionPane.showMessageDialog(this, "SVP entrer vos donneés");
        } else {
            if (com_re.getSelectedItem().equals("idAdministrateur")) {
                rs = db.querySelectAll("administrateur", "idAdministrateur LIKE '%" + txt_rech.getText() + "%' ");
                table_admin.setModel(new Gestion_biblio(rs));
            } else if (com_re.getSelectedItem().equals("Nom")) {
                rs = db.querySelectAll("administrateur", "Nom LIKE '%" + txt_rech.getText() + "%' ");
                table_admin.setModel(new Gestion_biblio(rs));
            } else if (com_re.getSelectedItem().equals("Prénom")) {
                rs = db.querySelectAll("administrateur", "Prénom LIKE '%" + txt_rech.getText() + "%' ");
                table_admin.setModel(new Gestion_biblio(rs));
            } else if (com_re.getSelectedItem().equals("Email")) {
                rs = db.querySelectAll("administrateur", "Email LIKE '%" + txt_rech.getText() + "%' ");
                table_admin.setModel(new Gestion_biblio(rs));

            } else if (com_re.getSelectedItem().equals("Type")) {
                rs = db.querySelectAll("administrateur", "type LIKE '%" + txt_rech.getText() + "%' ");
                table_admin.setModel(new Gestion_biblio(rs));

            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (txt_nom.getText().equals("") || txt_prenom.getText().equals("") || txt_email.getText().equals("")
            || txt_mot_passe.getText().equals("")|| compty.getSelectedItem().equals("Typpppe") ) {
            JOptionPane.showMessageDialog(this, "SVP entrer les informations complètes");
        }else{
            String id = String.valueOf(table_admin.getValueAt(table_admin.getSelectedRow(), 0));
            if (JOptionPane.showConfirmDialog(this, "Etes-vous sûr que vous voulez supprimer ?", "attention!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                db.queryDelete("administrateur", "idAdministrateur=" + id);
            } else {
                return;
            }
            table1();
            pp5.setText("Supprimer avec succès");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (txt_nom.getText().equals("") || txt_prenom.getText().equals("") || txt_email.getText().equals("")
            || txt_mot_passe.getText().equals("")|| compty.getSelectedItem().equals("Typpppe")) {
            JOptionPane.showMessageDialog(this, "SVP entrer les informations complètes");
        } else {
            String[] colon = {"Nom","Prénom","Email","Mot_passe","type"};
            String[] inf = {txt_nom.getText(), txt_prenom.getText(), txt_email.getText(), txt_mot_passe.getText(), compty.getSelectedItem().toString()};
            String id = String.valueOf(table_admin.getValueAt(table_admin.getSelectedRow(), 0));
            System.out.println(db.queryUpdate("administrateur", colon, inf, "idAdministrateur='" + id + "'"));
            table1();
            actualiser();
            pp5.setText("Modifié avec succès");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ( txt_nom.getText().equals("") || txt_prenom.getText().equals("") || txt_email.getText().equals("")
            || txt_mot_passe.getText().equals("")|| compty.getSelectedItem().equals("Typpppe")) {
            JOptionPane.showMessageDialog(this, "SVP entrer les informations complètes");
        } else {
            String[] colon = {"Nom","Prénom","Email","Mot_passe","type"};
            String[] inf = {txt_nom.getText(), txt_prenom.getText(), txt_email.getText(), txt_mot_passe.getText(), compty.getSelectedItem().toString()};
            System.out.println(db.queryInsert("administrateur", colon, inf));
            table1();
            actualiser();
            pp5.setText("ajouter avec succès");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prenomActionPerformed

    private void txt_mot_passeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mot_passeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mot_passeActionPerformed

    private void table_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_adminMouseClicked
        txt_nom.setText(String.valueOf(table_admin.getValueAt(table_admin.getSelectedRow(), 1)));
        txt_prenom.setText(String.valueOf(table_admin.getValueAt(table_admin.getSelectedRow(), 2)));
        txt_email.setText(String.valueOf(table_admin.getValueAt(table_admin.getSelectedRow(), 3)));
        txt_mot_passe.setText(String.valueOf(table_admin.getValueAt(table_admin.getSelectedRow(), 4)));
        compty.setSelectedItem(String.valueOf(table_admin.getValueAt(table_admin.getSelectedRow(), 5)));
    }//GEN-LAST:event_table_adminMouseClicked

    private void table_adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_adminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_table_adminMouseEntered

    private void mvtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_mvtPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_mvtPropertyChange

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
           final int MAX_X = 450;
          final int MIN_X = 50;
          
          Thread animation = new Thread(new Runnable(){
              @Override
              public void run() {
                    int x = 20;
                    int y = 30; 
                    while (true){
                          mvt.setLocation(x, y);
                          x +=10;
                          
                          try{
                              Thread.sleep(200);
                          }catch(Exception e){
                              
                              
                          }
              }
                  
                  
                  
              }   
          });
          animation.start(); 
    }//GEN-LAST:event_formWindowOpened

              
              
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> com_re;
    private javax.swing.JComboBox<String> compty;
    private javax.swing.JLabel date;
    private javax.swing.JLabel heure;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel mvt;
    private javax.swing.JLabel pp5;
    private javax.swing.JTable table_admin;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_mot_passe;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_prenom;
    private javax.swing.JTextField txt_rech;
    // End of variables declaration//GEN-END:variables
}
